package ru.debajo.srrradio.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF86468c)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF35003f)
val md_theme_light_secondary = Color(0xFF6c586b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf5dbf1)
val md_theme_light_onSecondaryContainer = Color(0xFF251626)
val md_theme_light_tertiary = Color(0xFF825249)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad2)
val md_theme_light_onTertiaryContainer = Color(0xFF33110b)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1e1a1d)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1e1a1d)
val md_theme_light_surfaceVariant = Color(0xFFecdee8)
val md_theme_light_onSurfaceVariant = Color(0xFF4d444c)
val md_theme_light_outline = Color(0xFF7f747d)
val md_theme_light_inverseOnSurface = Color(0xFFf7eef2)
val md_theme_light_inverseSurface = Color(0xFF342f33)
val md_theme_light_inversePrimary = Color(0xFFf8acfb)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFf8acfb)
val md_theme_dark_onPrimary = Color(0xFF51145a)
val md_theme_dark_primaryContainer = Color(0xFF6b2e72)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd5ff)
val md_theme_dark_secondary = Color(0xFFd8bfd5)
val md_theme_dark_onSecondary = Color(0xFF3b2b3b)
val md_theme_dark_secondaryContainer = Color(0xFF534152)
val md_theme_dark_onSecondaryContainer = Color(0xFFf5dbf1)
val md_theme_dark_tertiary = Color(0xFFf5b8ad)
val md_theme_dark_onTertiary = Color(0xFF4c251e)
val md_theme_dark_tertiaryContainer = Color(0xFF673b33)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad2)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1a1d)
val md_theme_dark_onBackground = Color(0xFFe9e0e4)
val md_theme_dark_surface = Color(0xFF1e1a1d)
val md_theme_dark_onSurface = Color(0xFFe9e0e4)
val md_theme_dark_surfaceVariant = Color(0xFF4d444c)
val md_theme_dark_onSurfaceVariant = Color(0xFFd0c3cc)
val md_theme_dark_outline = Color(0xFF998e96)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1a1d)
val md_theme_dark_inverseSurface = Color(0xFFe9e0e4)
val md_theme_dark_inversePrimary = Color(0xFF86468c)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF725572)
val error = Color(0xFFba1b1b)
val color68 = Color(0xFFEED4C7)
val color68Harmonize = true